version: '3.3'

services:
  db:
    image: mysql:8.0.29
    container_name: proj2-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=****
      - MYSQL_USER=****
      - MYSQL_PASSWORD=****
      - MYSQL_DATABASE=*****
    ports:
      - #*****
    restart: always